language: node_js
node_js:
  - "stable"
cache:
  directories:
    - ~/.npm
    - .jest
install: yarn install
before_script:
  - npm install -g npm@latest
script:
  - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
  - npx expo publish --non-interactive